export const SET_USER = 'SET_USER'
export const SET_SPEAKERS = 'SET_SPEAKERS'
export const SET_SPEAKER = 'SET_SPEAKER'
export const SET_TALKS = 'SET_TALKS'
export const SET_TALK = 'SET_TALK'
export const SET_FEEDBACK = 'SET_FEEDBACK'
export const SET_FEEDBACKS = 'SET_FEEDBACKS'
export const SET_CONFIG = 'SET_CONFIG'
